name: Flujo de trabajo para construir y publicar artefactos

on:
  workflow_dispatch:
  push:
    branches: [antmunsan2]
  pull_request:
    branches: [antmunsan2]

jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      GITHUB_LOGIN: ${{ github.actor }}
      GITHUB_PACKAGES: ${{ secrets.GHTOKEN }}
      GITHUB_OAUTH: ${{ secrets.GHTOKEN }}
    steps:
      - name: Clonando el repositorio y estableciendo el espacio de trabajo
        uses: actions/checkout@v3

      - name: Se configura Java para el job de construcción
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '16'

      - name: Construyendo el artefacto
        run: |
          chmod +x gradlew
          ./gradlew assemble
          echo antmunsan2

      - name: Se publica el artefacto
        run: |
          chmod +x gradlew
          ./gradlew publish
          echo antmunsan2
